#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication surfaceFeatureEdges \
    ship5415-hull-and-box.stl \
    ship5415-hull-and-box.ftr

runApplication cartesianMesh
runApplication checkMesh

#------------------------------------------------------------------------------
