#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

#------------------------------------------------------------------------------

wclean libso meshLibrary
wclean all executables
wclean all utilities

#------------------------------------------------------------------------------
