#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication preparePar
runParallel cartesianMesh 4
runParallel checkMesh 4
if [ "$WM_PROJECT" = "OpenFOAM" ]
then
runApplication reconstructParMesh -constant -fullMatch
else
runApplication reconstructParMesh -zeroTime
fi
