#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication preparePar
runParallel cartesianMesh
runParallel checkMesh

runApplication reconstructParMesh -constant -fullMatch
## runApplication reconstructParMesh -zeroTime

#------------------------------------------------------------------------------
