/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2005-2007 Franjo Juretic
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

\*---------------------------------------------------------------------------*/

#include "polyMeshGenAddressing.H"
#include "DynList.H"
#include "helperFunctions.H"
#include "demandDrivenData.H"

#include <omp.h>

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

// * * * * * * * * * * * * * Private Member Functions  * * * * * * * * * * * //

void polyMeshGenAddressing::calcEdges() const
{
    if( edgesPtr_ )
    {
        FatalErrorIn("polyMeshGenAddressing::calcEdges() const")
            << "edges already calculated"
            << abort(FatalError);
    }
    else
    {
        const faceListPMG& faces = mesh_.faces();
        const VRWGraph& pointFaces = this->pointFaces();
        
        edgesPtr_ = new edgeList();
        label nEdges(0);
        labelList nfe(faces.size());
        
        const label nThreads = 3 * omp_get_num_procs();
        labelList nEdgesForThread(nThreads);
        
        # pragma omp parallel num_threads(nThreads) if( faces.size() > 1000 )
        {
            LongList<edge> edgesHelper;
            
            # pragma omp for schedule(static)
            forAll(faces, faceI)
            {
                const face& f = faces[faceI];
                
                forAll(f, pI)
                {
                    const edge fe = f.faceEdge(pI);
                    const label s = fe.start();
                    const label e = fe.end();
                    
                    DynList<label> edgeFaces;
                    
                    bool store(true);
                    
                    //- find all faces attached to this edge
                    //- store the edge in case the face faceI is the face
                    //- with the smallest label
                    forAllRow(pointFaces, s, pfI)
                    {
                        const label ofI = pointFaces(s, pfI);
                        const face& of = faces[ofI];
                        
                        if( of.which(e) < 0 )
                            continue;
                        if( ofI < faceI )
                        {
                            store = false;
                            break;
                        }
                        
                        edgeFaces.append(ofI);
                    }
                    
                    if( store )
                        edgesHelper.append(fe);
                }
            }
            
            //- this enables other threads to see the number of edges
            //- generated by each thread
            nEdgesForThread[omp_get_thread_num()] = edgesHelper.size();
            
            # pragma omp critical
            nEdges += edgesHelper.size();
            
            # pragma omp barrier
            
            # pragma omp master
            edgesPtr_->setSize(nEdges);
            
            # pragma omp barrier
            
            //- find the starting position of the edges generated by this thread
            //- in the global list of edges
            label localStart(0);
            for(label i=0;i<omp_get_thread_num();++i)
                localStart += nEdgesForThread[i];
            
            //- store edges into the global list
            forAll(edgesHelper, i)
                edgesPtr_->operator[](localStart+i) = edgesHelper[i];
        }
    }
}

// * * * * * * * * * * * * * * * Member Functions  * * * * * * * * * * * * * //

const edgeList& polyMeshGenAddressing::edges() const
{
    if( !edgesPtr_ )
        calcEdges();

    return *edgesPtr_;
}

void polyMeshGenAddressing::clearOutEdges()
{
    deleteDemandDrivenData(edgesPtr_);
}


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// ************************************************************************* //
